services:
  server:
    image: pia-mpc
    tty: true
    cpus: 0.0
    cap_add:
    - NET_ADMIN
    volumes:
    - "../..:/workspaces/pia-mpc"
    - "${CUDA_HOME:?}:/opt/cuda-${CUDA_VERSION:?}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  client:
    extends: server
